name: Check test site.
on:
  workflow_dispatch:

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://wcnightlysmoketest.bluehost-and-a8c.com/ready1/"
        expected-statuses: "200,301"
